name: Load CSVs to Snowflake

on:
  workflow_dispatch:

jobs:
  test_connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-linux_x86_64.bash
          bash snowsql-linux_x86_64.bash

      - name: Verify SnowSQL
        run: snowsql -v

      - name: Test Snowflake Connection
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}

        run: |
          snowsql \
            -d ${{ secrets.SNOWFLAKE_DATABASE }} \
            -s ${{ secrets.SNOWFLAKE_SCHEMA }} \
            -w ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
            -r ${{ secrets.SNOWFLAKE_ROLE }} \
            -q "SELECT CURRENT_VERSION();"
