name: Load CSVs to Snowflake

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hello
        run: echo "GitHub Actions is working!"
